import { 
  ClubBudgetState, 
  MonthDef, 
  MonthSummary, 
  YearlyBudgetSummary, 
  RoomTier, 
  CustomExpense,
  TmFeeDetails,
  MemberEconomics,
  RoomEconomics,
  RoomTierSummary,
  ExpenseEconomics,
  BreakEvenAnalysis,
  BreakEvenCurvePoint,
  BreakEvenSimulationPoint
} from '../types';

export const DEFAULT_MONTHS: MonthDef[] = [
  { id: '2026-07', name: 'July', shortName: 'Jul', year: 2026, termSemester: 1 },
  { id: '2026-08', name: 'August', shortName: 'Aug', year: 2026, termSemester: 1 },
  { id: '2026-09', name: 'September', shortName: 'Sep', year: 2026, termSemester: 1 },
  { id: '2026-10', name: 'October', shortName: 'Oct', year: 2026, termSemester: 1 },
  { id: '2026-11', name: 'November', shortName: 'Nov', year: 2026, termSemester: 1 },
  { id: '2026-12', name: 'December', shortName: 'Dec', year: 2026, termSemester: 1 },
  { id: '2027-01', name: 'January', shortName: 'Jan', year: 2027, termSemester: 2 },
  { id: '2027-02', name: 'February', shortName: 'Feb', year: 2027, termSemester: 2 },
  { id: '2027-03', name: 'March', shortName: 'Mar', year: 2027, termSemester: 2 },
  { id: '2027-04', name: 'April', shortName: 'Apr', year: 2027, termSemester: 2 },
  { id: '2027-05', name: 'May', shortName: 'May', year: 2027, termSemester: 2 },
  { id: '2027-06', name: 'June', shortName: 'Jun', year: 2027, termSemester: 2 },
];

export const INITIAL_ROOM_TIERS: RoomTier[] = [
  { id: 'tier-1', name: '2x Big Room', pricePerMonth: 180, monthsCount: 10, comment: '90 € + 90 €' },
  { id: 'tier-2', name: '2x Small Room', pricePerMonth: 150, monthsCount: 2, comment: '75 € + 75 €' },
];

export const INITIAL_EXPENSES: CustomExpense[] = [
  {
    id: 'exp-google-one',
    name: 'Google One',
    category: 'recurring',
    amount: 9.99,
    frequency: 'monthly',
    comment: 'For virtual meetings and cloud storage',
    description: 'For virtual meetings and cloud storage',
  },
  {
    id: 'exp-materials',
    name: 'Materials',
    category: 'recurring',
    amount: 12.00,
    frequency: 'monthly',
    comment: 'Printing, stationery, ribbons, trophies',
    description: 'Printing, stationery, ribbons, trophies',
  },
  {
    id: 'exp-unexpected',
    name: 'Unexpected expenses',
    category: 'recurring',
    amount: 8.00,
    frequency: 'monthly',
    comment: 'Broken timekeeper lights, broken laptop charger, etc.',
    description: 'Broken timekeeper lights, broken laptop charger, etc.',
  },
  {
    id: 'exp-club-contest',
    name: 'Club Contest',
    category: 'one-time',
    amount: 60.00,
    frequency: 'one-time',
    comment: 'Printing, trophies, certificates',
    description: 'Printing, trophies, certificates',
  },
];

export const INITIAL_BUDGET_STATE: ClubBudgetState = {
  clubName: 'Munich Business Speakers',
  fiscalYear: '2026-2027',
  currency: '€',
  
  monthlyClubFeeEUR: 20.00,
  monthlyTmDuesUSD: 12.00,
  usdToEurRate: 0.87,
  vatRatePercent: 19.0, // 19% VAT
  
  defaultFullMembers: 19,
  
  roomTiers: INITIAL_ROOM_TIERS,
  
  expenses: INITIAL_EXPENSES,
};

/**
 * 1. Toastmasters Pass-through Unit Economics
 * Calculates full breakdown of TM fee per member (Base USD -> EUR -> VAT -> Total).
 * Handles negative, zero, and extreme parameters safely.
 */
export function calculateTmUnitFeeDetails(
  monthlyTmDuesUSD: number,
  usdToEurRate: number,
  vatRatePercent: number
): TmFeeDetails {
  const baseDuesUSD = Math.max(0, Number(monthlyTmDuesUSD) || 0);
  const rate = Math.max(0, Number(usdToEurRate) || 0);
  const vatRate = Math.max(0, Number(vatRatePercent) || 0);

  const rawConvertedEUR = baseDuesUSD * rate;
  const vatAmountEUR = rawConvertedEUR * (vatRate / 100);
  const totalTmFeePerMemberEUR = rawConvertedEUR + vatAmountEUR;

  return {
    baseDuesUSD,
    usdToEurRate: rate,
    rawConvertedEUR,
    vatRatePercent: vatRate,
    vatAmountEUR,
    totalTmFeePerMemberEUR,
  };
}

/**
 * Convenience wrapper returning single unit fee number
 */
export function calculateTmUnitFeeEUR(
  monthlyTmDuesUSD: number,
  usdToEurRate: number,
  vatRatePercent: number
): number {
  return calculateTmUnitFeeDetails(monthlyTmDuesUSD, usdToEurRate, vatRatePercent).totalTmFeePerMemberEUR;
}

/**
 * 2. Member Unit Contribution & Income Economics
 * Evaluates net margins, contribution splits, and total income generated by membership base.
 */
export function calculateMemberEconomics(
  monthlyClubFeeEUR: number,
  tmFeePerMemberEUR: number,
  defaultFullMembers: number
): MemberEconomics {
  const clubFee = Math.max(0, Number(monthlyClubFeeEUR) || 0);
  const tmFee = Math.max(0, Number(tmFeePerMemberEUR) || 0);
  const members = Math.max(0, Number(defaultFullMembers) || 0);

  const netMarginPerMemberEUR = clubFee - tmFee;
  const netMarginPerMemberYearlyEUR = netMarginPerMemberEUR * 12;
  const isDeficitMargin = netMarginPerMemberEUR < 0;

  const totalMonthlyIncome = members * clubFee;
  const totalAnnualIncome = totalMonthlyIncome * 12;

  // Split visual percentages
  let tmPercentage = 0;
  let localPercentage = 0;
  if (clubFee > 0) {
    tmPercentage = Math.min(100, Math.max(0, (tmFee / clubFee) * 100));
    localPercentage = Math.max(0, 100 - tmPercentage);
  } else if (tmFee > 0) {
    tmPercentage = 100;
    localPercentage = 0;
  }

  return {
    monthlyClubFeeEUR: clubFee,
    tmFeePerMemberEUR: tmFee,
    netMarginPerMemberEUR,
    netMarginPerMemberYearlyEUR,
    isDeficitMargin,
    tmPercentage,
    localPercentage,
    totalMonthlyIncome,
    totalAnnualIncome,
  };
}

/**
 * 3. Room Rent & Venue Leasing Economics
 * Maps configured tiers across the 12 calendar months, computing totals, averages, and allocation coverage.
 */
export function calculateRoomEconomics(
  roomTiers: RoomTier[],
  months: MonthDef[] = DEFAULT_MONTHS
): RoomEconomics {
  const totalMonthsInYear = months.length;
  let allocatedMonthsCounter = 0;
  const resolvedRoomPrices: Record<string, number> = {};
  
  const tierSummaries: RoomTierSummary[] = (roomTiers || []).map((tier) => {
    const monthsCount = Math.max(0, Math.floor(Number(tier.monthsCount) || 0));
    const pricePerMonth = Math.max(0, Number(tier.pricePerMonth) || 0);
    return {
      id: tier.id || `tier-${Math.random()}`,
      name: tier.name || 'Unnamed Venue Tier',
      pricePerMonth,
      monthsCount,
      annualCost: pricePerMonth * monthsCount,
      comment: tier.comment || tier.description || '',
      description: tier.description || tier.comment || '',
    };
  });

  const totalAllocatedMonths = tierSummaries.reduce((sum, t) => sum + t.monthsCount, 0);
  const isAllocationComplete = totalAllocatedMonths === totalMonthsInYear;
  const unallocatedMonthsCount = Math.max(0, totalMonthsInYear - totalAllocatedMonths);
  const overallocatedMonthsCount = Math.max(0, totalAllocatedMonths - totalMonthsInYear);

  // Distribute prices sequentially across the calendar months
  for (const tier of tierSummaries) {
    for (let i = 0; i < tier.monthsCount && allocatedMonthsCounter < totalMonthsInYear; i++) {
      resolvedRoomPrices[months[allocatedMonthsCounter].id] = tier.pricePerMonth;
      allocatedMonthsCounter++;
    }
  }

  // Pad remaining unallocated months with 0 €
  while (allocatedMonthsCounter < totalMonthsInYear) {
    resolvedRoomPrices[months[allocatedMonthsCounter].id] = 0;
    allocatedMonthsCounter++;
  }

  // Total annual room expense is sum of the 12 active calendar months
  const totalAnnualRoomExpense = months.reduce((sum, m) => sum + (resolvedRoomPrices[m.id] || 0), 0);
  const monthlyAverageRoomExpense = totalMonthsInYear > 0 ? totalAnnualRoomExpense / totalMonthsInYear : 0;

  return {
    totalAllocatedMonths,
    isAllocationComplete,
    unallocatedMonthsCount,
    overallocatedMonthsCount,
    totalAnnualRoomExpense,
    monthlyAverageRoomExpense,
    resolvedRoomPrices,
    tierSummaries,
  };
}

/**
 * Backward compatibility helper for resolving room prices map
 */
export function resolveRoomPricesForMonths(
  months: MonthDef[],
  roomTiers: RoomTier[]
): Record<string, number> {
  return calculateRoomEconomics(roomTiers, months).resolvedRoomPrices;
}

/**
 * 4. Custom Operational & Event Expense Economics
 * Segregates recurring vs one-off expenses and computes annual costs.
 */
export function calculateExpenseEconomics(expenses: CustomExpense[]): ExpenseEconomics {
  const recurringExpenses: (CustomExpense & { annualCost: number })[] = [];
  const oneTimeExpenses: (CustomExpense & { annualCost: number })[] = [];

  let totalMonthlyRecurring = 0;
  let totalAnnualRecurring = 0;
  let totalAnnualOneTime = 0;

  for (const exp of expenses || []) {
    const amount = Math.max(0, Number(exp.amount) || 0);
    const sanitizedExp: CustomExpense = {
      id: exp.id || `exp-${Math.random()}`,
      name: exp.name || 'Unnamed Expense',
      category: exp.frequency === 'one-time' ? 'one-time' : 'recurring',
      frequency: exp.frequency === 'one-time' ? 'one-time' : 'monthly',
      amount,
      comment: exp.comment || exp.description || '',
      description: exp.description || exp.comment || '',
    };

    if (sanitizedExp.frequency === 'monthly') {
      const annualCost = amount * 12;
      recurringExpenses.push({ ...sanitizedExp, annualCost });
      totalMonthlyRecurring += amount;
      totalAnnualRecurring += annualCost;
    } else {
      const annualCost = amount;
      oneTimeExpenses.push({ ...sanitizedExp, annualCost });
      totalAnnualOneTime += annualCost;
    }
  }

  const totalAnnualCustomExpenses = totalAnnualRecurring + totalAnnualOneTime;

  return {
    recurringExpenses,
    oneTimeExpenses,
    totalMonthlyRecurring,
    totalAnnualRecurring,
    totalAnnualOneTime,
    totalAnnualCustomExpenses,
  };
}

/**
 * 5. Break-Even & Sensitivity Analysis
 * Calculates the exact member count and minimum club fee needed to cover fixed overhead.
 * Handles division by zero, non-achievable margins, and zero-member edge cases cleanly.
 */
export function calculateBreakEvenAnalysis(
  yearlyFixedCosts: number,
  monthlyClubFeeEUR: number,
  tmFeePerMemberEUR: number,
  defaultFullMembers: number
): BreakEvenAnalysis {
  const fixedCosts = Math.max(0, Number(yearlyFixedCosts) || 0);
  const clubFee = Math.max(0, Number(monthlyClubFeeEUR) || 0);
  const tmFee = Math.max(0, Number(tmFeePerMemberEUR) || 0);
  const members = Math.max(0, Number(defaultFullMembers) || 0);

  const netMarginPerMemberMonthly = clubFee - tmFee;
  const netMarginPerMemberYearly = netMarginPerMemberMonthly * 12;

  let isBreakEvenAchievable = false;
  let breakEvenFullMembersNeeded: number | null = null;
  let statusMessage = '';

  if (fixedCosts === 0) {
    isBreakEvenAchievable = true;
    breakEvenFullMembersNeeded = 0;
    statusMessage = 'Zero fixed overhead: break-even achieved with 0.00 members.';
  } else if (netMarginPerMemberYearly > 0) {
    isBreakEvenAchievable = true;
    breakEvenFullMembersNeeded = fixedCosts / netMarginPerMemberYearly;
    const surplus = members - breakEvenFullMembersNeeded;
    if (surplus >= 0) {
      statusMessage = `Safe margin: Club is currently +${surplus.toFixed(2)} members above break-even.`;
    } else {
      statusMessage = `Deficit risk: Club needs ${Math.abs(surplus).toFixed(2)} more paying members to break even.`;
    }
  } else if (netMarginPerMemberYearly === 0) {
    isBreakEvenAchievable = false;
    breakEvenFullMembersNeeded = null;
    statusMessage = 'Club fee equals TM fee (zero margin): cannot cover venue or overhead at any member count.';
  } else {
    isBreakEvenAchievable = false;
    breakEvenFullMembersNeeded = null;
    statusMessage = 'Negative unit margin: each additional member increases total deficit.';
  }

  let breakEvenClubFeeNeeded: number | null = null;
  if (members > 0) {
    breakEvenClubFeeNeeded = tmFee + (fixedCosts / (members * 12));
  }

  const currentMembersSurplus = breakEvenFullMembersNeeded !== null 
    ? members - breakEvenFullMembersNeeded 
    : -Infinity;

  return {
    yearlyFixedCosts: fixedCosts,
    netMarginPerMemberYearly,
    isBreakEvenAchievable,
    breakEvenFullMembersNeeded,
    breakEvenClubFeeNeeded,
    currentMembersSurplus,
    statusMessage,
  };
}

/**
 * Calculates the exact continuous break-even monthly fee required for a specific member count.
 * Formula: F_be(M) = tmFeePerMemberEUR + (yearlyFixedCosts / (M * 12))
 */
export function calculateBreakEvenFeeForMembers(
  members: number,
  yearlyFixedCosts: number,
  tmFeePerMemberEUR: number
): number {
  const safeMembers = Math.max(0.01, Number(members) || 0);
  const fixed = Math.max(0, Number(yearlyFixedCosts) || 0);
  const tmFee = Math.max(0, Number(tmFeePerMemberEUR) || 0);
  return tmFee + (fixed / (safeMembers * 12));
}

/**
 * Calculates the exact number of members required to break even given a specific monthly fee.
 * Formula: M_be(F) = yearlyFixedCosts / (12 * (monthlyClubFeeEUR - tmFeePerMemberEUR))
 */
export function calculateBreakEvenMembersForFee(
  monthlyClubFeeEUR: number,
  yearlyFixedCosts: number,
  tmFeePerMemberEUR: number
): number | null {
  const fee = Math.max(0, Number(monthlyClubFeeEUR) || 0);
  const tmFee = Math.max(0, Number(tmFeePerMemberEUR) || 0);
  const fixed = Math.max(0, Number(yearlyFixedCosts) || 0);
  const unitMargin = fee - tmFee;

  if (fixed === 0) return 0;
  if (unitMargin <= 0) return null; // Never breaks even with zero or negative margin
  return fixed / (unitMargin * 12);
}

/**
 * Calculates comprehensive simulation metrics at any arbitrary (Members, Fee) coordinate on the chart.
 */
export function calculateSimulationPoint(
  members: number,
  monthlyClubFeeEUR: number,
  yearlyFixedCosts: number,
  tmFeePerMemberEUR: number
): BreakEvenSimulationPoint {
  const safeMembers = Math.max(0, Number(members) || 0);
  const safeFee = Math.max(0, Number(monthlyClubFeeEUR) || 0);
  const fixed = Math.max(0, Number(yearlyFixedCosts) || 0);
  const tmFee = Math.max(0, Number(tmFeePerMemberEUR) || 0);

  const annualRevenue = safeMembers * safeFee * 12;
  const annualTmExpenses = safeMembers * tmFee * 12;
  const annualExpenses = annualTmExpenses + fixed;
  const annualNetProfitLoss = annualRevenue - annualExpenses;
  const monthlyNetProfitLoss = annualNetProfitLoss / 12;
  const unitMarginEUR = safeFee - tmFee;

  const breakEvenFeeEUR = calculateBreakEvenFeeForMembers(safeMembers, fixed, tmFee);
  const breakEvenMembersNeeded = calculateBreakEvenMembersForFee(safeFee, fixed, tmFee);
  const isSurplus = annualNetProfitLoss >= 0;

  return {
    members: safeMembers,
    monthlyFeeEUR: safeFee,
    annualRevenue,
    annualExpenses,
    annualNetProfitLoss,
    monthlyNetProfitLoss,
    unitMarginEUR,
    breakEvenFeeEUR,
    breakEvenMembersNeeded,
    isSurplus,
  };
}

/**
 * Generates an array of curve sample points for plotting the continuous break-even boundary.
 */
export function generateBreakEvenCurvePoints(
  yearlyFixedCosts: number,
  tmFeePerMemberEUR: number,
  minMembers: number = 2,
  maxMembers: number = 50,
  stepCount: number = 100
): BreakEvenCurvePoint[] {
  const points: BreakEvenCurvePoint[] = [];
  const start = Math.max(0.5, minMembers);
  const end = Math.max(start + 1, maxMembers);
  const step = (end - start) / Math.max(1, stepCount);

  for (let i = 0; i <= stepCount; i++) {
    const members = start + i * step;
    const breakEvenFeeEUR = calculateBreakEvenFeeForMembers(members, yearlyFixedCosts, tmFeePerMemberEUR);
    points.push({ members, breakEvenFeeEUR });
  }

  return points;
}

/**
 * 6. Main Unified Calculation Engine for the Yearly Budget
 * Integrates all domain economics into a single high-performance summary model.
 */
export function calculateYearlyBudget(
  state: ClubBudgetState,
  months: MonthDef[] = DEFAULT_MONTHS
): YearlyBudgetSummary {
  // Domain 1: TM pass-through fee
  const tmFeeDetails = calculateTmUnitFeeDetails(
    state.monthlyTmDuesUSD,
    state.usdToEurRate,
    state.vatRatePercent
  );

  // Domain 2: Member economics
  const memberEconomics = calculateMemberEconomics(
    state.monthlyClubFeeEUR,
    tmFeeDetails.totalTmFeePerMemberEUR,
    state.defaultFullMembers
  );

  // Domain 3: Room economics
  const roomEconomics = calculateRoomEconomics(state.roomTiers, months);

  // Domain 4: Custom expense economics
  const expenseEconomics = calculateExpenseEconomics(state.expenses);

  // Domain 5: Break-even analysis
  const yearlyFixedCosts = roomEconomics.totalAnnualRoomExpense + expenseEconomics.totalAnnualCustomExpenses;
  const breakEven = calculateBreakEvenAnalysis(
    yearlyFixedCosts,
    state.monthlyClubFeeEUR,
    tmFeeDetails.totalTmFeePerMemberEUR,
    state.defaultFullMembers
  );

  let totalIncome = 0;
  let totalExpenses = 0;
  let totalTmDuesExpense = 0;
  let totalRoomRentExpense = 0;
  let totalOtherExpenses = 0;
  let runningCashFlow = 0;

  const monthSummaries: MonthSummary[] = months.map((month, idx) => {
    const fullMembers = state.defaultFullMembers;
    const totalMembers = fullMembers;

    // Monthly income
    const membershipIncome = fullMembers * state.monthlyClubFeeEUR;
    const monthIncome = membershipIncome;

    // Monthly expenses
    const tmDuesExpense = totalMembers * tmFeeDetails.totalTmFeePerMemberEUR;
    const roomRentExpense = roomEconomics.resolvedRoomPrices[month.id] ?? 0;

    const itemizedExpenses: Record<string, number> = {};
    let sumCustomExpenses = 0;

    for (const exp of state.expenses) {
      const amount = Math.max(0, Number(exp.amount) || 0);
      if (exp.frequency === 'monthly') {
        itemizedExpenses[exp.id] = amount;
        sumCustomExpenses += amount;
      } else {
        // One-time expenses occur once (default allocated to Month 1)
        if (idx === 0) {
          itemizedExpenses[exp.id] = amount;
          sumCustomExpenses += amount;
        } else {
          itemizedExpenses[exp.id] = 0;
        }
      }
    }

    const monthExpenses = tmDuesExpense + roomRentExpense + sumCustomExpenses;
    const netProfitLoss = monthIncome - monthExpenses;
    runningCashFlow += netProfitLoss;

    totalIncome += monthIncome;
    totalExpenses += monthExpenses;
    totalTmDuesExpense += tmDuesExpense;
    totalRoomRentExpense += roomRentExpense;
    totalOtherExpenses += sumCustomExpenses;

    return {
      month,
      fullMembers,
      totalMembers,
      tmFeePerMemberEUR: tmFeeDetails.totalTmFeePerMemberEUR,
      membershipIncome,
      totalIncome: monthIncome,
      tmDuesExpense,
      roomRentExpense,
      itemizedExpenses,
      totalExpenses: monthExpenses,
      netProfitLoss,
      cumulativeCashFlow: runningCashFlow,
    };
  });

  const netProfitLoss = totalIncome - totalExpenses;
  const averageMonthlyProfitLoss = months.length > 0 ? netProfitLoss / months.length : 0;
  const profitMarginPercent = totalIncome > 0 ? (netProfitLoss / totalIncome) * 100 : 0;

  return {
    months: monthSummaries,
    totalIncome,
    totalExpenses,
    netProfitLoss,
    averageMonthlyProfitLoss,
    profitMarginPercent,
    totalTmDuesExpense,
    totalRoomRentExpense,
    totalOtherExpenses,
    
    // Sub-domain models for full component reuse
    tmFeeDetails,
    memberEconomics,
    roomEconomics,
    expenseEconomics,
    breakEven,
    breakEvenAnalysis: breakEven,

    // Backward compatibility convenience properties
    breakEvenFullMembersNeeded: breakEven.breakEvenFullMembersNeeded ?? 0,
    breakEvenClubFeeNeeded: breakEven.breakEvenClubFeeNeeded ?? state.monthlyClubFeeEUR,
  };
}

/**
 * Consistent Currency Formatter (de-DE locale: comma for decimals, dot for thousands)
 */
export function formatCurrency(
  amount: number, 
  currency: string = '€', 
  fractionDigits: number = 2
): string {
  const num = Number(amount) || 0;
  const isNegative = num < 0;
  const absVal = Math.abs(num);
  
  const formatted = absVal.toLocaleString('de-DE', {
    minimumFractionDigits: fractionDigits,
    maximumFractionDigits: fractionDigits,
  });

  return isNegative ? `-${formatted} ${currency}` : `${formatted} ${currency}`;
}

export function formatNumber(val: number, fractionDigits: number = 2): string {
  const num = Number(val) || 0;
  return num.toLocaleString('de-DE', {
    minimumFractionDigits: fractionDigits,
    maximumFractionDigits: fractionDigits,
  });
}

export function formatMembersCount(val: number): string {
  const num = Number(val) || 0;
  return num % 1 === 0 
    ? num.toString() 
    : num.toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function formatCompactNumber(val: number): string {
  const num = Number(val) || 0;
  return num.toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function formatPercent(val: number, fractionDigits: number = 1): string {
  const num = Number(val) || 0;
  return `${num.toLocaleString('de-DE', {
    minimumFractionDigits: fractionDigits,
    maximumFractionDigits: fractionDigits,
  })}%`;
}

